version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn clean compile assembly:single
artifacts:
  files:
    - target/hera-prod-bundle-jar-with-dependencies.jar
    - appspec.yml
  discard-paths: yes
